<?php

namespace App\Http\Controllers;

use Inertia\Inertia;

class KewpaDirectoryController extends Controller
{
    public function index()
    {
        $forms = [
            // ═══════════════════════════════════════════════════════════
            // LOGISTIK & PENERIMAAN
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-1 / PA-1A',
                'name'          => 'Penerimaan Aset',
                'name_en'       => 'Asset Receiving',
                'stage'         => 'Logistik & Penerimaan',
                'route_list'    => 'receivings.index',
                'route_view'    => 'receivings.kewpa1',
                'route_view_params' => ['receiving' => 'param'],
                'route_download' => 'receivings.kewpa1.download',
                'route_download_params' => ['receiving' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Borang penerimaan aset alih dan tak alih (KEW.PA-1) dan borang penerimaan aset tak alih (PA-1A)',
            ],

            // ═══════════════════════════════════════════════════════════
            // PENDAFTARAN ASET
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-2',
                'name'          => 'Pendaftaran Aset',
                'name_en'       => 'Asset Registration',
                'stage'         => 'Pendaftaran Aset',
                'route_list'    => 'assets.index',
                'route_view'    => 'assets.kewpa2',
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.kewpa2.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Butiran pendaftaran aset termasuk maklumat perolehan, spesifikasi, dan gambar aset',
            ],
            [
                'number'        => 'PA-3',
                'name'          => 'Kad Aset',
                'name_en'       => 'Asset Card',
                'stage'         => 'Pendaftaran Aset',
                'route_list'    => 'assets.index',
                'route_view'    => 'assets.kewpa3',
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.kewpa3.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Kad individu untuk setiap aset yang mengandungi sejarah, penyelenggaraan, dan naik taraf',
            ],

            // ═══════════════════════════════════════════════════════════
            // PERGERAKAN & PEMERIKSAAN
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-6',
                'name'          => 'Daftar Pergerakan',
                'name_en'       => 'Asset Movement Register',
                'stage'         => 'Pergerakan & Pemeriksaan',
                'route_list'    => 'transfers.index',
                'route_view'    => 'assets.kewpa6',
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.kewpa6.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Merekod pergerakan aset antara lokasi, pegangan, dan jabatan',
            ],
            [
                'number'        => 'PA-9',
                'name'          => 'Aduan Kerosakan',
                'name_en'       => 'Damage Report',
                'stage'         => 'Pergerakan & Pemeriksaan',
                'route_list'    => 'damage-reports.index',
                'route_view'    => 'damage-reports.kewpa9.download', // direct download
                'route_view_params' => ['damageReport' => 'param'],
                'route_download' => 'damage-reports.kewpa9.download',
                'route_download_params' => ['damageReport' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Laporan aduan kerosakan aset untuk tujuan tuntutan dan tindakan pembaikan',
            ],
            [
                'number'        => 'PA-9A',
                'name'          => 'Pinjaman Aset',
                'name_en'       => 'Asset Loan / Placement',
                'stage'         => 'Pergerakan & Pemeriksaan',
                'route_list'    => 'placements.index',
                'route_view'    => 'assets.kewpa9a',
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.kewpa9a.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Borang pinjaman aset kepada kakitangan atau pelajar untuk kegunaan sementara',
            ],
            [
                'number'        => 'PA-10',
                'name'          => 'Pemeriksaan Harta Tetap',
                'name_en'       => 'Fixed Asset Inspection',
                'stage'         => 'Pergerakan & Pemeriksaan',
                'route_list'    => 'inspections.index',
                'route_view'    => 'assets.kewpa10',
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.kewpa10.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Rekod pemeriksaan berkala harta tetap untuk memastikan keadaan dan lokasi aset tepat',
            ],
            [
                'number'        => 'PA-11',
                'name'          => 'Pemeriksaan Inventori',
                'name_en'       => 'Inventory Inspection',
                'stage'         => 'Pergerakan & Pemeriksaan',
                'route_list'    => 'inspections.index',
                'route_view'    => 'inspections.kewpa11',
                'route_view_params' => [],
                'route_download' => 'inspections.kewpa11.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Laporan pemeriksaan inventori (aset alih) dengan daftar KEW.PA-3, lokasi, kuantiti, dan keadaan',
            ],
            [
                'number'        => 'PA-12',
                'name'          => 'Perakuan Pemeriksaan Tahunan',
                'name_en'       => 'Annual Inspection Certificate',
                'stage'         => 'Pergerakan & Pemeriksaan',
                'route_list'    => 'reports.kewpa12',
                'route_view'    => 'reports.kewpa12',
                'route_view_params' => [],
                'route_download' => 'reports.kewpa12.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Perakuan tahunan pemeriksaan fizikal aset alih dan tak alih (admin)',
                'admin_only'    => true,
            ],

            // ═══════════════════════════════════════════════════════════
            // PENYELENGGARAAN
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-13',
                'name'          => 'Senarai Penyelenggaraan',
                'name_en'       => 'Maintenance List',
                'stage'         => 'Penyelenggaraan',
                'route_list'    => 'maintenances.index',
                'route_view'    => 'assets.maintenances.kewpa13.download', // direct download
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.maintenances.kewpa13.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Senarai harta tetap yang memerlukan penyelenggaraan termasuk kontrak, kos, dan status',
            ],
            [
                'number'        => 'PA-14',
                'name'          => 'Daftar Penyelenggaraan',
                'name_en'       => 'Maintenance Register',
                'stage'         => 'Penyelenggaraan',
                'route_list'    => 'maintenances.index',
                'route_view'    => 'maintenances.kewpa14',
                'route_view_params' => [],
                'route_download' => 'maintenances.kewpa14.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Daftar penyelenggaraan harta tetap dengan 6 lajur: tarikh, butir, kontrak, syarikat, kos, tandatangan (a-f)',
            ],

            // ═══════════════════════════════════════════════════════════
            // PELUPUSAN & JUALAN
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-15',
                'name'          => 'Pelantikan Jawatankuasa Pemeriksa Pelupusan',
                'name_en'       => 'Disposal Inspection Committee',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'committee-appointments.index',
                'route_view'    => null,
                'route_download' => null,
                'status'        => 'implemented',
                'description'   => 'Lantikan jawatankuasa pemeriksa pelupusan aset alih universiti (surat format)',
            ],
            [
                'number'        => 'PA-16',
                'name'          => 'Perakuan Pelupusan Kenderaan',
                'name_en'       => 'Vehicle Disposal Assessment',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'vehicle-disposals.index',
                'route_view'    => 'assets.vehicle-disposal.kewpa16',
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.vehicle-disposal.kewpa16.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Penilaian kenderaan yang dicadang untuk pelupusan termasuk anggaran nilai dan syor',
            ],
            [
                'number'        => 'PA-17',
                'name'          => 'Permohonan Pelupusan',
                'name_en'       => 'Disposal Application',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposals.index',
                'route_view'    => 'assets.disposals.kewpa17.download', // direct download
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.disposals.kewpa17.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Permohonan/perakuan pelupusan harta UTM — dokumen utama pelupusan aset',
            ],
            [
                'number'        => 'PA-18',
                'name'          => 'Sijil Pemusnahan',
                'name_en'       => 'Destruction Certificate',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposals.index',
                'route_view'    => 'disposals.kewpa18',
                'route_view_params' => [],
                'route_download' => 'disposals.kewpa18.download',
                'route_download_params' => ['disposal' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Sijil pengesahan pemusnahan aset alih universiti — Tanam/Bakar/Tenggelam dengan tandatangan dual',
            ],
            [
                'number'        => 'PA-19',
                'name'          => 'Sijil Pelupusan',
                'name_en'       => 'Disposal Certificate',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposals.index',
                'route_view'    => 'disposals.kewpa19',
                'route_view_params' => [],
                'route_download' => 'disposals.kewpa19.download',
                'route_download_params' => ['disposal' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Sijil pelupusan harta tetap dengan jadual 10 lajur dan 3 tandatangan AJK',
            ],
            [
                'number'        => 'PA-20',
                'name'          => 'Laporan Pelupusan Aset Tahunan',
                'name_en'       => 'Annual Disposal Report',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'reports.kewpa20',
                'route_view'    => 'reports.kewpa20',
                'route_view_params' => [],
                'route_download' => 'reports.kewpa20.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Laporan tahunan semua pelupusan aset yang telah diluluskan (admin)',
                'admin_only'    => true,
            ],
            [
                'number'        => 'PA-21',
                'name'          => 'Notis Jualan',
                'name_en'       => 'Sale Notification',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa21',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa21.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Notis penjualan aset secara tawaran, sebutharga, atau lelongan',
            ],
            [
                'number'        => 'PA-22',
                'name'          => 'Iklan Jualan',
                'name_en'       => 'Sale Advertisement',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa22',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa22.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Iklan awam untuk jualan aset melalui tawaran atau lelongan',
            ],
            [
                'number'        => 'PA-23',
                'name'          => 'Surat Tawaran Jualan',
                'name_en'       => 'Sale Award Letter',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa23',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa23.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Surat tawaran kepada pembeli yang berjaya dalam jualan aset',
            ],
            [
                'number'        => 'PA-24',
                'name'          => 'Sijil Jualan',
                'name_en'       => 'Sale Certificate',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa24',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa24.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Sijil rasmi penjualan aset kepada pembeli',
            ],
            [
                'number'        => 'PA-25',
                'name'          => 'Pindah Milik Jualan',
                'name_en'       => 'Asset Transfer After Sale',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa25',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa25.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Dokumen pindah milik aset kepada pembeli selepas jualan selesai',
            ],
            [
                'number'        => 'PA-26',
                'name'          => 'D.O. Jualan',
                'name_en'       => 'Delivery Order',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa26',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa26.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Dokumen penghantaran aset yang telah dijual kepada pembeli',
            ],
            [
                'number'        => 'PA-27',
                'name'          => 'Laporan Jualan',
                'name_en'       => 'Sale Report',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa27',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa27.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Laporan lengkap proses jualan aset termasuk keputusan dan keputusan',
            ],
            [
                'number'        => 'PA-27A',
                'name'          => 'Ringkasan Jualan',
                'name_en'       => 'Sale Summary',
                'stage'         => 'Pelupusan & Jualan',
                'route_list'    => 'disposal-sales.index',
                'route_view'    => 'disposal-sales.kewpa27a',
                'route_view_params' => ['sale' => 'param'],
                'route_download' => 'disposal-sales.kewpa27a.download',
                'route_download_params' => ['sale' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Ringkasan maklumat jualan aset untuk rekod dan rujukan',
            ],

            // ═══════════════════════════════════════════════════════════
            // KEHILANGAN
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-28',
                'name'          => 'Laporan Awal Kehilangan',
                'name_en'       => 'Initial Loss Report',
                'stage'         => 'Kehilangan',
                'route_list'    => 'loss-reports.index',
                'route_view'    => 'assets.loss-reports.kewpa28.download', // direct download
                'route_view_params' => ['asset' => 'param'],
                'route_download' => 'assets.loss-reports.kewpa28.download',
                'route_download_params' => ['asset' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Laporan awal kehilangan aset alih universiti — langkah pertama dalam rantaian kehilangan',
            ],
            [
                'number'        => 'PA-29',
                'name'          => 'Pelantikan Jawatankuasa Penyiasat',
                'name_en'       => 'Loss Investigation Committee',
                'stage'         => 'Kehilangan',
                'route_list'    => 'committee-appointments.index',
                'route_view'    => null,
                'route_download' => null,
                'status'        => 'implemented',
                'description'   => 'Pelantikan jawatankuasa penyiasat kehilangan aset alih universiti (surat format)',
            ],
            [
                'number'        => 'PA-30',
                'name'          => 'Laporan Akhir Kehilangan',
                'name_en'       => 'Final Loss Report',
                'stage'         => 'Kehilangan',
                'route_list'    => 'loss-reports.index',
                'route_view'    => null, // nested under asset+lossReport — accessible from loss report detail
                'route_view_params' => [],
                'route_download' => null, // needs asset+lossReport params
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Laporan akhir siasatan kehilangan aset alih — 8 seksyen: butiran aset, kehilangan, polis, saksi, pematuhan, pencegahan, rumusan, syor',
            ],
            [
                'number'        => 'PA-31',
                'name'          => 'Sijil Hapuskira',
                'name_en'       => 'Write-off Certificate',
                'stage'         => 'Kehilangan',
                'route_list'    => 'loss-reports.index',
                'route_view'    => 'loss-reports.kewpa31',
                'route_view_params' => [],
                'route_download' => 'loss-reports.kewpa31.download',
                'route_download_params' => ['lossReport' => 'param'],
                'status'        => 'implemented',
                'description'   => 'Sijil hapuskira aset alih universiti dengan rujukan JK dan tandatangan Pegawai Aset',
            ],
            [
                'number'        => 'PA-32',
                'name'          => 'Laporan Tindakan Kehilangan',
                'name_en'       => 'Annual Loss Action Report',
                'stage'         => 'Kehilangan',
                'route_list'    => 'loss-reports.index',
                'route_view'    => 'loss-reports.kewpa32',
                'route_view_params' => [],
                'route_download' => 'loss-reports.kewpa32.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Laporan tahunan tindakan kehilangan aset alih universiti — dikumpul mengikut tahun dengan ringkasan',
            ],

            // ═══════════════════════════════════════════════════════════
            // LAPORAN TAHUNAN (Admin)
            // ═══════════════════════════════════════════════════════════
            [
                'number'        => 'PA-4',
                'name'          => 'Senarai Harta Tetap',
                'name_en'       => 'Fixed Asset Register',
                'stage'         => 'Laporan Tahunan',
                'route_list'    => 'reports.kewpa4',
                'route_view'    => 'reports.kewpa4',
                'route_view_params' => [],
                'route_download' => 'reports.kewpa4.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Senarai lengkap harta tetap (aset) mengikut kategori dan lokasi (admin)',
                'admin_only'    => true,
            ],
            [
                'number'        => 'PA-5',
                'name'          => 'Senarai Inventori',
                'name_en'       => 'Inventory Register',
                'stage'         => 'Laporan Tahunan',
                'route_list'    => 'reports.kewpa5',
                'route_view'    => 'reports.kewpa5',
                'route_view_params' => [],
                'route_download' => 'reports.kewpa5.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Senarai inventori aset alih dan tak alih untuk tujuan audit tahunan (admin)',
                'admin_only'    => true,
            ],
            [
                'number'        => 'PA-7',
                'name'          => 'Laporan Kedudukan Aset',
                'name_en'       => 'Asset Position Report',
                'stage'         => 'Laporan Tahunan',
                'route_list'    => 'reports.kewpa7',
                'route_view'    => 'reports.kewpa7',
                'route_view_params' => [],
                'route_download' => 'reports.kewpa7.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Laporan kedudukan aset mengikut lokasi, status, dan pegangan (admin)',
                'admin_only'    => true,
            ],
            [
                'number'        => 'PA-8',
                'name'          => 'Laporan Tahunan',
                'name_en'       => 'Annual Report',
                'stage'         => 'Laporan Tahunan',
                'route_list'    => 'reports.kewpa8',
                'route_view'    => 'reports.kewpa8',
                'route_view_params' => [],
                'route_download' => 'reports.kewpa8.download',
                'route_download_params' => [],
                'status'        => 'implemented',
                'description'   => 'Laporan tahunan komprehensif pengurusan aset untuk pihak pengurusan (admin)',
                'admin_only'    => true,
            ],
        ];

        return Inertia::render('Kewpa/Index', [
            'forms' => $forms,
        ]);
    }
}
